export const practicesData = {
  title: "Mes pratiques : Brunella, belle escorte pour votre plaisir",
  description:
    "Retrouvez une liste non exhaustive de mes différentes pratiques",
  intro:
    "Cela répondra à la majorité de vos interrogations, et si vous lisez mes services érotiques vous découvrirez comment vous faire plaisir en me faisant plaisir",

  whatIDo: {
    title: "CE QUE JE FAIS…",
    items: [
      "GFE : Girl Friend Experience",
      "PSE : Porn Star Experience",
      "Extraball: plusieurs rapport en 1h",
      "Accompagnement en Club Échangiste / Sauna Libertin",
      "Massage Erotique naturiste",
      "Massage BodyBody Thaï",
      "Massage en Duo à 4 mains",
      "Massage du Lingam",
      "Massage Couple",
      "Show Web Cam visio",
      "Strip Tease / Effeuillage burlesque",
      "Longs Préliminaires",
      "Jeux de rôles / Scénario HOT",
      "Paroles coquines",
      "Kamasutra et 69 (péché mignon pour la levrette)",
      "Être dominée (avec respect)",
      "Fétish pieds",
      "BDSM: Maîtresse Domina Initiation SM Soft/Hard",
      "Facesitting",
      "Handjob",
      "Douce ou sauvage / Ange ou Démon",
      "Branlette / Branlette espagnole",
      "Fellation nature ou protégée",
      "Finition corporelle (sauf le visage)",
      "Sex toys (pour moi et pour vous)",
      "Travail anal / Massage prostatique",
      "French Kiss : Embrasser avec la langue",
      "Trio HOT : Couple ou HFF",
      "Conversation excitante : mots cru et fessées",
      "Anal (sur moi ou sur vous)",
      "Cunnilingus et Anulingus (sur moi)",
      "Fist (vaginal uniquement)",
      "Douche dorée (donneuse)",
    ],
  },

  whatIDontDo: {
    title: "Ce que je ne fait pas...",
    items: [
      "Anulingus (sur vous)",
      "Être attachée (trop risqué)",
      "Je ne fais pas crédit !",
      "Je ne suis pas assistante sociale !",
      "Je ne fais pas de téléphone rose",
      "Je ne fais pas de tchat d'SMS érotique interminable…",
      "Je ne réponds pas aux appels masqués, ni aux fixes.",
      "Je ne négocie pas mes tarifs!!!",
      "Je ne vide pas les « fond de poches »!",
      "Je ne fais pas de chantage, et n'accepte pas vos informations de CB pour vider vos comptes bancaires sur internet!! ( malgré l'insistance de certain soumis )",
    ],
  },

  whatIDontLike: {
    title: "Ce que je n'aime pas…",
    items: [
      "Le tutoiement direct au téléphone et les langages trop familiers",
      "La brutalité, les grossièretés et le manque de respect",
      "Que l'on me bave ou crache dessus",
      "Que l'on me pince ou mordille les tétons",
      "Ceux qui retiennent leur jouissance pour faire durer le plaisir au maximum pour au final ne plus réussir à jouir",
      "Ceux qui prennent un RDV pour 30 min et qui ont besoin de 2h pour jouir",
      "Gorge profonde forcée avec les mains sur la tête",
    ],
  },
};